title: ""
description: "Researcher in RL and stochastic control"
url: "https://amidimohsen.github.io"
baseurl: ""    # very important for username.github.io sites
theme: minima  # or minimal-mistakes-jekyll, etc.
